### ISSUE TITLE
Is it possible to add scripts?

### ISSUE THREAD

**Issue by knagasaka** [baozg/Potato_C88#2]
Hi Zhigui,

Thank you very much for your previous detailed answers!

Sorry if I am mistaken, but I don't think I can find the following script.
Besides, "# combine" in STEP4 (haplotype-aware genetic mapping) may be missing some details.

Would it be possible to add a script?
I would really appreciate it if you could.

Thank you in advance,
Kyoka

------------------------------------------
readnum2fitPoly.pl
fitPoly.R
fitPoly2genotype.pl
cor_diplotig.py
complement.pl
reformat.pl

**Comment by baozg** [comment]
Hi Kyoka,

Sorry for the late response. I already add the missing script to the GitHub. For the combine step, just `cat` all the unitig groups and reformat into the hifiasm requirement input. 

I will reformat all the code into the Snakemake pipeline and add out data for better reproductivity in the next month.


Best regards
Zhigui

**Comment by knagasaka** [comment]
Hi Zhigui,

Thank you so much for your help!
Your work is excellent.
I can learn a lot from your work.
I am waiting for your future updates.

Best regards,
Kyoka
