### ISSUE TITLE
Question for Figure 2A

### ISSUE THREAD

**Issue by YvonneennovY** [baozg/Potato_C88#3]
Hi Zhigui,

Thank you very much for your outstanding work, which has allowed me to learn a lot!

I am a bit confused about the analysis of Figure 2A in your article. You mentioned that you used the longest haplotype as the reference to detect the SNP/indel. So how you compared SNP/indel density among the six different haplotype pairs? 
Would it be possible to share the relevant scripts for Figure 2A? 
I would be immensely grateful.

Best wishes,
Yvonne

**Comment by baozg** [comment]
If we assume the hap1 as a reference, then align the hap1 and hap2 to the hap1 and call variants. In this case, all variants in hap2 will be detected. If you compare hap2 and hap3, then only the heterozygous variants will be considered.

**Comment by YvonneennovY** [comment]
Thank you for your detailed response!
