### ISSUE TITLE
there is no "03_target_query_correlation.R" file in script

### ISSUE THREAD

**Issue by socialhang** [baozg/Potato_C88#4]
Hi @baozg!

It's nice to talk to you again. I found that the script 03_target_query_correlation.R is missing in the script folder, so the step `Rscript script/03_target_query_correlation.R query.readnum target.readnum readnum.correlation.out` cannot be executed. Could you please add this script?

With best wishes！
hang

**Comment by baozg** [comment]
Sorry, it should be `11_target_query_correlation.R`, you may need install `WGCNA` by yourself

**Comment by socialhang** [comment]
Thanks a lot!
